<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="final_project_modeling" nsURI="http://www.example.org/final_project_modeling"
    nsPrefix="final_project_modeling">
  <eClassifiers xsi:type="ecore:EClass" name="App">
    <eStructuralFeatures xsi:type="ecore:EReference" name="screen" lowerBound="1"
        upperBound="-1" eType="#//Screen" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" lowerBound="1" upperBound="-1"
        eType="#//Query" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexSearchQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="SearchRecipesByIngredientsQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="GetRecipeInformationQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="GetRandomRecipesQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="SearchIngredientsQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConvertAmountsQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="GetIngredientSubstitutes" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="SearchMenuItemsQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="WinePairingQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="Query">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        upperBound="-1" eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="possiblePreceedingQueries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
