/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import no.ntnu.tdt4250.recipe.Header;
import no.ntnu.tdt4250.recipe.Ingredients;
import no.ntnu.tdt4250.recipe.Page;
import no.ntnu.tdt4250.recipe.Section;
import no.ntnu.tdt4250.recipe.UnitOfMeasure;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.example.mydsl.services.RecipeGrammarAccess;

@SuppressWarnings("all")
public class RecipeFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private RecipeGrammarAccess _recipeGrammarAccess;

  protected void _format(final Page page, @Extension final IFormattableDocument document) {
    EList<Section> _section = page.getSection();
    for (final Section section : _section) {
      document.<Section>format(section);
    }
    document.<Header>format(page.getHeader());
  }

  protected void _format(final Ingredients ingredients, @Extension final IFormattableDocument document) {
    document.<UnitOfMeasure>format(ingredients.getUnittoggle());
  }

  @XbaseGenerated
  public void format(final Object ingredients, final IFormattableDocument document) {
    if (ingredients instanceof XtextResource) {
      _format((XtextResource)ingredients, document);
      return;
    } else if (ingredients instanceof Ingredients) {
      _format((Ingredients)ingredients, document);
      return;
    } else if (ingredients instanceof Page) {
      _format((Page)ingredients, document);
      return;
    } else if (ingredients instanceof EObject) {
      _format((EObject)ingredients, document);
      return;
    } else if (ingredients == null) {
      _format((Void)null, document);
      return;
    } else if (ingredients != null) {
      _format(ingredients, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(ingredients, document).toString());
    }
  }
}
