/*
 * generated by Xtext 2.36.0
 */
package no.ntnu.tdt4250.recipe.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RecipeDSLUiModule extends AbstractRecipeDSLUiModule {

	public RecipeDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
