/*
 * generated by Xtext 2.36.0
 */
package no.ntnu.tdt4250.recipe.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RecipeDSLStandaloneSetup extends RecipeDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new RecipeDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
