/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RecipeGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cInstructionsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cInstructionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cInstructionsInstructionsCrossReference_4_0 = (CrossReference)cInstructionsAssignment_4.eContents().get(0);
		private final RuleCall cInstructionsInstructionsEStringParserRuleCall_4_0_1 = (RuleCall)cInstructionsInstructionsCrossReference_4_0.eContents().get(1);
		private final Keyword cIngredientsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cIngredientsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cIngredientsIngredientsCrossReference_6_0 = (CrossReference)cIngredientsAssignment_6.eContents().get(0);
		private final RuleCall cIngredientsIngredientsEStringParserRuleCall_6_0_1 = (RuleCall)cIngredientsIngredientsCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSectionKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cSectionAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cSectionSectionParserRuleCall_7_2_0 = (RuleCall)cSectionAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cSectionAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cSectionSectionParserRuleCall_7_3_1_0 = (RuleCall)cSectionAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cHeaderKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cHeaderAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cHeaderHeaderParserRuleCall_9_0 = (RuleCall)cHeaderAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Page returns Page:
		//    'Page'
		//    name=EString
		//    '{'
		//        'instructions' instructions=[Instructions|EString]
		//        'ingredients' ingredients=[Ingredients|EString]
		//        ('section' '{' section+=Section ( "," section+=Section)* '}' )?
		//        'header' header=Header
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Page'
		//name=EString
		//'{'
		//    'instructions' instructions=[Instructions|EString]
		//    'ingredients' ingredients=[Ingredients|EString]
		//    ('section' '{' section+=Section ( "," section+=Section)* '}' )?
		//    'header' header=Header
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Page'
		public Keyword getPageKeyword_0() { return cPageKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'instructions'
		public Keyword getInstructionsKeyword_3() { return cInstructionsKeyword_3; }
		
		//instructions=[Instructions|EString]
		public Assignment getInstructionsAssignment_4() { return cInstructionsAssignment_4; }
		
		//[Instructions|EString]
		public CrossReference getInstructionsInstructionsCrossReference_4_0() { return cInstructionsInstructionsCrossReference_4_0; }
		
		//EString
		public RuleCall getInstructionsInstructionsEStringParserRuleCall_4_0_1() { return cInstructionsInstructionsEStringParserRuleCall_4_0_1; }
		
		//'ingredients'
		public Keyword getIngredientsKeyword_5() { return cIngredientsKeyword_5; }
		
		//ingredients=[Ingredients|EString]
		public Assignment getIngredientsAssignment_6() { return cIngredientsAssignment_6; }
		
		//[Ingredients|EString]
		public CrossReference getIngredientsIngredientsCrossReference_6_0() { return cIngredientsIngredientsCrossReference_6_0; }
		
		//EString
		public RuleCall getIngredientsIngredientsEStringParserRuleCall_6_0_1() { return cIngredientsIngredientsEStringParserRuleCall_6_0_1; }
		
		//('section' '{' section+=Section ( "," section+=Section)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'section'
		public Keyword getSectionKeyword_7_0() { return cSectionKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//section+=Section
		public Assignment getSectionAssignment_7_2() { return cSectionAssignment_7_2; }
		
		//Section
		public RuleCall getSectionSectionParserRuleCall_7_2_0() { return cSectionSectionParserRuleCall_7_2_0; }
		
		//( "," section+=Section)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//section+=Section
		public Assignment getSectionAssignment_7_3_1() { return cSectionAssignment_7_3_1; }
		
		//Section
		public RuleCall getSectionSectionParserRuleCall_7_3_1_0() { return cSectionSectionParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'header'
		public Keyword getHeaderKeyword_8() { return cHeaderKeyword_8; }
		
		//header=Header
		public Assignment getHeaderAssignment_9() { return cHeaderAssignment_9; }
		
		//Header
		public RuleCall getHeaderHeaderParserRuleCall_9_0() { return cHeaderHeaderParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Section");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIngredientsParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cInstructionsParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNutrientsParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Section returns Section:
		//    Ingredients | Instructions | Nutrients;
		@Override public ParserRule getRule() { return rule; }
		
		//Ingredients | Instructions | Nutrients
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Ingredients
		public RuleCall getIngredientsParserRuleCall_0() { return cIngredientsParserRuleCall_0; }
		
		//Instructions
		public RuleCall getInstructionsParserRuleCall_1() { return cInstructionsParserRuleCall_1; }
		
		//Nutrients
		public RuleCall getNutrientsParserRuleCall_2() { return cNutrientsParserRuleCall_2; }
	}
	public class InstructionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Instructions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInstructionsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOrderNumberKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOrderNumberAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOrderNumberEIntParserRuleCall_3_0 = (RuleCall)cOrderNumberAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Instructions returns Instructions:
		//    'Instructions'
		//    '{'
		//        'orderNumber' orderNumber=EInt
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Instructions'
		//'{'
		//    'orderNumber' orderNumber=EInt
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Instructions'
		public Keyword getInstructionsKeyword_0() { return cInstructionsKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'orderNumber'
		public Keyword getOrderNumberKeyword_2() { return cOrderNumberKeyword_2; }
		
		//orderNumber=EInt
		public Assignment getOrderNumberAssignment_3() { return cOrderNumberAssignment_3; }
		
		//EInt
		public RuleCall getOrderNumberEIntParserRuleCall_3_0() { return cOrderNumberEIntParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class IngredientsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Ingredients");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIngredientsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOrderNumberKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOrderNumberAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOrderNumberEIntParserRuleCall_3_0 = (RuleCall)cOrderNumberAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUnittoggleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUnittoggleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUnittoggleUnitOfMeasureParserRuleCall_4_1_0 = (RuleCall)cUnittoggleAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Ingredients returns Ingredients:
		//    'Ingredients'
		//    '{'
		//        'orderNumber' orderNumber=EInt
		//        ('unittoggle' unittoggle=UnitOfMeasure)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Ingredients'
		//'{'
		//    'orderNumber' orderNumber=EInt
		//    ('unittoggle' unittoggle=UnitOfMeasure)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Ingredients'
		public Keyword getIngredientsKeyword_0() { return cIngredientsKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'orderNumber'
		public Keyword getOrderNumberKeyword_2() { return cOrderNumberKeyword_2; }
		
		//orderNumber=EInt
		public Assignment getOrderNumberAssignment_3() { return cOrderNumberAssignment_3; }
		
		//EInt
		public RuleCall getOrderNumberEIntParserRuleCall_3_0() { return cOrderNumberEIntParserRuleCall_3_0; }
		
		//('unittoggle' unittoggle=UnitOfMeasure)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'unittoggle'
		public Keyword getUnittoggleKeyword_4_0() { return cUnittoggleKeyword_4_0; }
		
		//unittoggle=UnitOfMeasure
		public Assignment getUnittoggleAssignment_4_1() { return cUnittoggleAssignment_4_1; }
		
		//UnitOfMeasure
		public RuleCall getUnittoggleUnitOfMeasureParserRuleCall_4_1_0() { return cUnittoggleUnitOfMeasureParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class HeaderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Header");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHeaderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cBasicinformationKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBasicinformationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBasicinformationBasicInformationParserRuleCall_3_0 = (RuleCall)cBasicinformationAssignment_3.eContents().get(0);
		private final Keyword cRecipetitleKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRecipetitleAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRecipetitleTitleParserRuleCall_5_0 = (RuleCall)cRecipetitleAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cImageKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cImageAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cImageImageParserRuleCall_6_1_0 = (RuleCall)cImageAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Header returns Header:
		//    'Header'
		//    '{'
		//        'basicinformation' basicinformation=BasicInformation
		//        'recipetitle' recipetitle=Title
		//        ('image' image=Image)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Header'
		//'{'
		//    'basicinformation' basicinformation=BasicInformation
		//    'recipetitle' recipetitle=Title
		//    ('image' image=Image)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Header'
		public Keyword getHeaderKeyword_0() { return cHeaderKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'basicinformation'
		public Keyword getBasicinformationKeyword_2() { return cBasicinformationKeyword_2; }
		
		//basicinformation=BasicInformation
		public Assignment getBasicinformationAssignment_3() { return cBasicinformationAssignment_3; }
		
		//BasicInformation
		public RuleCall getBasicinformationBasicInformationParserRuleCall_3_0() { return cBasicinformationBasicInformationParserRuleCall_3_0; }
		
		//'recipetitle'
		public Keyword getRecipetitleKeyword_4() { return cRecipetitleKeyword_4; }
		
		//recipetitle=Title
		public Assignment getRecipetitleAssignment_5() { return cRecipetitleAssignment_5; }
		
		//Title
		public RuleCall getRecipetitleTitleParserRuleCall_5_0() { return cRecipetitleTitleParserRuleCall_5_0; }
		
		//('image' image=Image)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'image'
		public Keyword getImageKeyword_6_0() { return cImageKeyword_6_0; }
		
		//image=Image
		public Assignment getImageAssignment_6_1() { return cImageAssignment_6_1; }
		
		//Image
		public RuleCall getImageImageParserRuleCall_6_1_0() { return cImageImageParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class NutrientsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Nutrients");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNutrientsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOrderNumberKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOrderNumberAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOrderNumberEIntParserRuleCall_3_0 = (RuleCall)cOrderNumberAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPercentagetoggleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPercentagetoggleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPercentagetogglePercentageAmountToggleParserRuleCall_4_1_0 = (RuleCall)cPercentagetoggleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cVitaminsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cVitaminsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cVitaminsVitaminsParserRuleCall_5_1_0 = (RuleCall)cVitaminsAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMacronutrientsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMacronutrientsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMacronutrientsMacronutrientsParserRuleCall_6_1_0 = (RuleCall)cMacronutrientsAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Nutrients returns Nutrients:
		//    'Nutrients'
		//    '{'
		//        'orderNumber' orderNumber=EInt
		//        ('percentagetoggle' percentagetoggle=PercentageAmountToggle)?
		//        ('vitamins' vitamins=Vitamins)?
		//        ('macronutrients' macronutrients=Macronutrients)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Nutrients'
		//'{'
		//    'orderNumber' orderNumber=EInt
		//    ('percentagetoggle' percentagetoggle=PercentageAmountToggle)?
		//    ('vitamins' vitamins=Vitamins)?
		//    ('macronutrients' macronutrients=Macronutrients)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Nutrients'
		public Keyword getNutrientsKeyword_0() { return cNutrientsKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'orderNumber'
		public Keyword getOrderNumberKeyword_2() { return cOrderNumberKeyword_2; }
		
		//orderNumber=EInt
		public Assignment getOrderNumberAssignment_3() { return cOrderNumberAssignment_3; }
		
		//EInt
		public RuleCall getOrderNumberEIntParserRuleCall_3_0() { return cOrderNumberEIntParserRuleCall_3_0; }
		
		//('percentagetoggle' percentagetoggle=PercentageAmountToggle)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'percentagetoggle'
		public Keyword getPercentagetoggleKeyword_4_0() { return cPercentagetoggleKeyword_4_0; }
		
		//percentagetoggle=PercentageAmountToggle
		public Assignment getPercentagetoggleAssignment_4_1() { return cPercentagetoggleAssignment_4_1; }
		
		//PercentageAmountToggle
		public RuleCall getPercentagetogglePercentageAmountToggleParserRuleCall_4_1_0() { return cPercentagetogglePercentageAmountToggleParserRuleCall_4_1_0; }
		
		//('vitamins' vitamins=Vitamins)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'vitamins'
		public Keyword getVitaminsKeyword_5_0() { return cVitaminsKeyword_5_0; }
		
		//vitamins=Vitamins
		public Assignment getVitaminsAssignment_5_1() { return cVitaminsAssignment_5_1; }
		
		//Vitamins
		public RuleCall getVitaminsVitaminsParserRuleCall_5_1_0() { return cVitaminsVitaminsParserRuleCall_5_1_0; }
		
		//('macronutrients' macronutrients=Macronutrients)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'macronutrients'
		public Keyword getMacronutrientsKeyword_6_0() { return cMacronutrientsKeyword_6_0; }
		
		//macronutrients=Macronutrients
		public Assignment getMacronutrientsAssignment_6_1() { return cMacronutrientsAssignment_6_1; }
		
		//Macronutrients
		public RuleCall getMacronutrientsMacronutrientsParserRuleCall_6_1_0() { return cMacronutrientsMacronutrientsParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class PercentageAmountToggleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.PercentageAmountToggle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPercentageAmountToggleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPercentageAmountToggleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//PercentageAmountToggle returns PercentageAmountToggle:
		//    {PercentageAmountToggle}
		//    'PercentageAmountToggle'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{PercentageAmountToggle}
		//'PercentageAmountToggle'
		public Group getGroup() { return cGroup; }
		
		//{PercentageAmountToggle}
		public Action getPercentageAmountToggleAction_0() { return cPercentageAmountToggleAction_0; }
		
		//'PercentageAmountToggle'
		public Keyword getPercentageAmountToggleKeyword_1() { return cPercentageAmountToggleKeyword_1; }
	}
	public class VitaminsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Vitamins");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVitaminsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cVitaminKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cVitaminAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVitaminVitaminEnumRuleCall_4_0 = (RuleCall)cVitaminAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cVitaminAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cVitaminVitaminEnumRuleCall_5_1_0 = (RuleCall)cVitaminAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Vitamins returns Vitamins:
		//    'Vitamins'
		//    '{'
		//        'Vitamin' '{' Vitamin+=Vitamin ( "," Vitamin+=Vitamin)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Vitamins'
		//'{'
		//    'Vitamin' '{' Vitamin+=Vitamin ( "," Vitamin+=Vitamin)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Vitamins'
		public Keyword getVitaminsKeyword_0() { return cVitaminsKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'Vitamin'
		public Keyword getVitaminKeyword_2() { return cVitaminKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//Vitamin+=Vitamin
		public Assignment getVitaminAssignment_4() { return cVitaminAssignment_4; }
		
		//Vitamin
		public RuleCall getVitaminVitaminEnumRuleCall_4_0() { return cVitaminVitaminEnumRuleCall_4_0; }
		
		//( "," Vitamin+=Vitamin)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//Vitamin+=Vitamin
		public Assignment getVitaminAssignment_5_1() { return cVitaminAssignment_5_1; }
		
		//Vitamin
		public RuleCall getVitaminVitaminEnumRuleCall_5_1_0() { return cVitaminVitaminEnumRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class MacronutrientsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Macronutrients");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMacronutrientsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMacronutrientsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Macronutrients returns Macronutrients:
		//    {Macronutrients}
		//    'Macronutrients'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Macronutrients}
		//'Macronutrients'
		public Group getGroup() { return cGroup; }
		
		//{Macronutrients}
		public Action getMacronutrientsAction_0() { return cMacronutrientsAction_0; }
		
		//'Macronutrients'
		public Keyword getMacronutrientsKeyword_1() { return cMacronutrientsKeyword_1; }
	}
	public class UnitOfMeasureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.UnitOfMeasure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUnitOfMeasureAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUnitOfMeasureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//UnitOfMeasure returns UnitOfMeasure:
		//    {UnitOfMeasure}
		//    'UnitOfMeasure'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{UnitOfMeasure}
		//'UnitOfMeasure'
		public Group getGroup() { return cGroup; }
		
		//{UnitOfMeasure}
		public Action getUnitOfMeasureAction_0() { return cUnitOfMeasureAction_0; }
		
		//'UnitOfMeasure'
		public Keyword getUnitOfMeasureKeyword_1() { return cUnitOfMeasureKeyword_1; }
	}
	public class BasicInformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.BasicInformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBasicInformationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBasicInformationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//BasicInformation returns BasicInformation:
		//    {BasicInformation}
		//    'BasicInformation'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{BasicInformation}
		//'BasicInformation'
		public Group getGroup() { return cGroup; }
		
		//{BasicInformation}
		public Action getBasicInformationAction_0() { return cBasicInformationAction_0; }
		
		//'BasicInformation'
		public Keyword getBasicInformationKeyword_1() { return cBasicInformationKeyword_1; }
	}
	public class TitleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Title");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTitleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTitleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Title returns Title:
		//    {Title}
		//    'Title'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Title}
		//'Title'
		public Group getGroup() { return cGroup; }
		
		//{Title}
		public Action getTitleAction_0() { return cTitleAction_0; }
		
		//'Title'
		public Keyword getTitleKeyword_1() { return cTitleKeyword_1; }
	}
	public class ImageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Image");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cImageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cImageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Image returns Image:
		//    {Image}
		//    'Image'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Image}
		//'Image'
		public Group getGroup() { return cGroup; }
		
		//{Image}
		public Action getImageAction_0() { return cImageAction_0; }
		
		//'Image'
		public Keyword getImageKeyword_1() { return cImageKeyword_1; }
	}
	
	public class VitaminElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Recipe.Vitamin");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cVITAMIN_AEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cVITAMIN_AVITAMIN_AKeyword_0_0 = (Keyword)cVITAMIN_AEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cVITAMIN_B1EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cVITAMIN_B1VITAMIN_B1Keyword_1_0 = (Keyword)cVITAMIN_B1EnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cVITAMIN_B2EnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cVITAMIN_B2VITAMIN_B2Keyword_2_0 = (Keyword)cVITAMIN_B2EnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cVITAMIN_B3EnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cVITAMIN_B3VITAMIN_B3Keyword_3_0 = (Keyword)cVITAMIN_B3EnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cVITAMIN_B5EnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cVITAMIN_B5VITAMIN_B5Keyword_4_0 = (Keyword)cVITAMIN_B5EnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cVITAMIN_B6EnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cVITAMIN_B6VITAMIN_B6Keyword_5_0 = (Keyword)cVITAMIN_B6EnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cVITAMIN_B12EnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cVITAMIN_B12VITAMIN_B12Keyword_6_0 = (Keyword)cVITAMIN_B12EnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cVITAMIN_CEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cVITAMIN_CVITAMIN_CKeyword_7_0 = (Keyword)cVITAMIN_CEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cVITAMIN_EEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cVITAMIN_EVITAMIN_EKeyword_8_0 = (Keyword)cVITAMIN_EEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cVITAMIN_KEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cVITAMIN_KVITAMIN_KKeyword_9_0 = (Keyword)cVITAMIN_KEnumLiteralDeclaration_9.eContents().get(0);
		
		//enum Vitamin returns Vitamin:
		//                VITAMIN_A = 'VITAMIN_A' | VITAMIN_B1 = 'VITAMIN_B1' | VITAMIN_B2 = 'VITAMIN_B2' | VITAMIN_B3 = 'VITAMIN_B3' | VITAMIN_B5 = 'VITAMIN_B5' | VITAMIN_B6 = 'VITAMIN_B6' | VITAMIN_B12 = 'VITAMIN_B12' | VITAMIN_C = 'VITAMIN_C' | VITAMIN_E = 'VITAMIN_E' | VITAMIN_K = 'VITAMIN_K';
		public EnumRule getRule() { return rule; }
		
		//VITAMIN_A = 'VITAMIN_A' | VITAMIN_B1 = 'VITAMIN_B1' | VITAMIN_B2 = 'VITAMIN_B2' | VITAMIN_B3 = 'VITAMIN_B3' | VITAMIN_B5 = 'VITAMIN_B5' | VITAMIN_B6 = 'VITAMIN_B6' | VITAMIN_B12 = 'VITAMIN_B12' | VITAMIN_C = 'VITAMIN_C' | VITAMIN_E = 'VITAMIN_E' | VITAMIN_K = 'VITAMIN_K'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//VITAMIN_A = 'VITAMIN_A'
		public EnumLiteralDeclaration getVITAMIN_AEnumLiteralDeclaration_0() { return cVITAMIN_AEnumLiteralDeclaration_0; }
		
		//'VITAMIN_A'
		public Keyword getVITAMIN_AVITAMIN_AKeyword_0_0() { return cVITAMIN_AVITAMIN_AKeyword_0_0; }
		
		//VITAMIN_B1 = 'VITAMIN_B1'
		public EnumLiteralDeclaration getVITAMIN_B1EnumLiteralDeclaration_1() { return cVITAMIN_B1EnumLiteralDeclaration_1; }
		
		//'VITAMIN_B1'
		public Keyword getVITAMIN_B1VITAMIN_B1Keyword_1_0() { return cVITAMIN_B1VITAMIN_B1Keyword_1_0; }
		
		//VITAMIN_B2 = 'VITAMIN_B2'
		public EnumLiteralDeclaration getVITAMIN_B2EnumLiteralDeclaration_2() { return cVITAMIN_B2EnumLiteralDeclaration_2; }
		
		//'VITAMIN_B2'
		public Keyword getVITAMIN_B2VITAMIN_B2Keyword_2_0() { return cVITAMIN_B2VITAMIN_B2Keyword_2_0; }
		
		//VITAMIN_B3 = 'VITAMIN_B3'
		public EnumLiteralDeclaration getVITAMIN_B3EnumLiteralDeclaration_3() { return cVITAMIN_B3EnumLiteralDeclaration_3; }
		
		//'VITAMIN_B3'
		public Keyword getVITAMIN_B3VITAMIN_B3Keyword_3_0() { return cVITAMIN_B3VITAMIN_B3Keyword_3_0; }
		
		//VITAMIN_B5 = 'VITAMIN_B5'
		public EnumLiteralDeclaration getVITAMIN_B5EnumLiteralDeclaration_4() { return cVITAMIN_B5EnumLiteralDeclaration_4; }
		
		//'VITAMIN_B5'
		public Keyword getVITAMIN_B5VITAMIN_B5Keyword_4_0() { return cVITAMIN_B5VITAMIN_B5Keyword_4_0; }
		
		//VITAMIN_B6 = 'VITAMIN_B6'
		public EnumLiteralDeclaration getVITAMIN_B6EnumLiteralDeclaration_5() { return cVITAMIN_B6EnumLiteralDeclaration_5; }
		
		//'VITAMIN_B6'
		public Keyword getVITAMIN_B6VITAMIN_B6Keyword_5_0() { return cVITAMIN_B6VITAMIN_B6Keyword_5_0; }
		
		//VITAMIN_B12 = 'VITAMIN_B12'
		public EnumLiteralDeclaration getVITAMIN_B12EnumLiteralDeclaration_6() { return cVITAMIN_B12EnumLiteralDeclaration_6; }
		
		//'VITAMIN_B12'
		public Keyword getVITAMIN_B12VITAMIN_B12Keyword_6_0() { return cVITAMIN_B12VITAMIN_B12Keyword_6_0; }
		
		//VITAMIN_C = 'VITAMIN_C'
		public EnumLiteralDeclaration getVITAMIN_CEnumLiteralDeclaration_7() { return cVITAMIN_CEnumLiteralDeclaration_7; }
		
		//'VITAMIN_C'
		public Keyword getVITAMIN_CVITAMIN_CKeyword_7_0() { return cVITAMIN_CVITAMIN_CKeyword_7_0; }
		
		//VITAMIN_E = 'VITAMIN_E'
		public EnumLiteralDeclaration getVITAMIN_EEnumLiteralDeclaration_8() { return cVITAMIN_EEnumLiteralDeclaration_8; }
		
		//'VITAMIN_E'
		public Keyword getVITAMIN_EVITAMIN_EKeyword_8_0() { return cVITAMIN_EVITAMIN_EKeyword_8_0; }
		
		//VITAMIN_K = 'VITAMIN_K'
		public EnumLiteralDeclaration getVITAMIN_KEnumLiteralDeclaration_9() { return cVITAMIN_KEnumLiteralDeclaration_9; }
		
		//'VITAMIN_K'
		public Keyword getVITAMIN_KVITAMIN_KKeyword_9_0() { return cVITAMIN_KVITAMIN_KKeyword_9_0; }
	}
	
	private final PageElements pPage;
	private final SectionElements pSection;
	private final InstructionsElements pInstructions;
	private final IngredientsElements pIngredients;
	private final HeaderElements pHeader;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final NutrientsElements pNutrients;
	private final PercentageAmountToggleElements pPercentageAmountToggle;
	private final VitaminsElements pVitamins;
	private final MacronutrientsElements pMacronutrients;
	private final VitaminElements eVitamin;
	private final UnitOfMeasureElements pUnitOfMeasure;
	private final BasicInformationElements pBasicInformation;
	private final TitleElements pTitle;
	private final ImageElements pImage;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RecipeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPage = new PageElements();
		this.pSection = new SectionElements();
		this.pInstructions = new InstructionsElements();
		this.pIngredients = new IngredientsElements();
		this.pHeader = new HeaderElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.pNutrients = new NutrientsElements();
		this.pPercentageAmountToggle = new PercentageAmountToggleElements();
		this.pVitamins = new VitaminsElements();
		this.pMacronutrients = new MacronutrientsElements();
		this.eVitamin = new VitaminElements();
		this.pUnitOfMeasure = new UnitOfMeasureElements();
		this.pBasicInformation = new BasicInformationElements();
		this.pTitle = new TitleElements();
		this.pImage = new ImageElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Recipe".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Page returns Page:
	//    'Page'
	//    name=EString
	//    '{'
	//        'instructions' instructions=[Instructions|EString]
	//        'ingredients' ingredients=[Ingredients|EString]
	//        ('section' '{' section+=Section ( "," section+=Section)* '}' )?
	//        'header' header=Header
	//    '}';
	public PageElements getPageAccess() {
		return pPage;
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}
	
	//Section returns Section:
	//    Ingredients | Instructions | Nutrients;
	public SectionElements getSectionAccess() {
		return pSection;
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}
	
	//Instructions returns Instructions:
	//    'Instructions'
	//    '{'
	//        'orderNumber' orderNumber=EInt
	//    '}';
	public InstructionsElements getInstructionsAccess() {
		return pInstructions;
	}
	
	public ParserRule getInstructionsRule() {
		return getInstructionsAccess().getRule();
	}
	
	//Ingredients returns Ingredients:
	//    'Ingredients'
	//    '{'
	//        'orderNumber' orderNumber=EInt
	//        ('unittoggle' unittoggle=UnitOfMeasure)?
	//    '}';
	public IngredientsElements getIngredientsAccess() {
		return pIngredients;
	}
	
	public ParserRule getIngredientsRule() {
		return getIngredientsAccess().getRule();
	}
	
	//Header returns Header:
	//    'Header'
	//    '{'
	//        'basicinformation' basicinformation=BasicInformation
	//        'recipetitle' recipetitle=Title
	//        ('image' image=Image)?
	//    '}';
	public HeaderElements getHeaderAccess() {
		return pHeader;
	}
	
	public ParserRule getHeaderRule() {
		return getHeaderAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Nutrients returns Nutrients:
	//    'Nutrients'
	//    '{'
	//        'orderNumber' orderNumber=EInt
	//        ('percentagetoggle' percentagetoggle=PercentageAmountToggle)?
	//        ('vitamins' vitamins=Vitamins)?
	//        ('macronutrients' macronutrients=Macronutrients)?
	//    '}';
	public NutrientsElements getNutrientsAccess() {
		return pNutrients;
	}
	
	public ParserRule getNutrientsRule() {
		return getNutrientsAccess().getRule();
	}
	
	//PercentageAmountToggle returns PercentageAmountToggle:
	//    {PercentageAmountToggle}
	//    'PercentageAmountToggle'
	//    ;
	public PercentageAmountToggleElements getPercentageAmountToggleAccess() {
		return pPercentageAmountToggle;
	}
	
	public ParserRule getPercentageAmountToggleRule() {
		return getPercentageAmountToggleAccess().getRule();
	}
	
	//Vitamins returns Vitamins:
	//    'Vitamins'
	//    '{'
	//        'Vitamin' '{' Vitamin+=Vitamin ( "," Vitamin+=Vitamin)* '}'
	//    '}';
	public VitaminsElements getVitaminsAccess() {
		return pVitamins;
	}
	
	public ParserRule getVitaminsRule() {
		return getVitaminsAccess().getRule();
	}
	
	//Macronutrients returns Macronutrients:
	//    {Macronutrients}
	//    'Macronutrients'
	//    ;
	public MacronutrientsElements getMacronutrientsAccess() {
		return pMacronutrients;
	}
	
	public ParserRule getMacronutrientsRule() {
		return getMacronutrientsAccess().getRule();
	}
	
	//enum Vitamin returns Vitamin:
	//                VITAMIN_A = 'VITAMIN_A' | VITAMIN_B1 = 'VITAMIN_B1' | VITAMIN_B2 = 'VITAMIN_B2' | VITAMIN_B3 = 'VITAMIN_B3' | VITAMIN_B5 = 'VITAMIN_B5' | VITAMIN_B6 = 'VITAMIN_B6' | VITAMIN_B12 = 'VITAMIN_B12' | VITAMIN_C = 'VITAMIN_C' | VITAMIN_E = 'VITAMIN_E' | VITAMIN_K = 'VITAMIN_K';
	public VitaminElements getVitaminAccess() {
		return eVitamin;
	}
	
	public EnumRule getVitaminRule() {
		return getVitaminAccess().getRule();
	}
	
	//UnitOfMeasure returns UnitOfMeasure:
	//    {UnitOfMeasure}
	//    'UnitOfMeasure'
	//    ;
	public UnitOfMeasureElements getUnitOfMeasureAccess() {
		return pUnitOfMeasure;
	}
	
	public ParserRule getUnitOfMeasureRule() {
		return getUnitOfMeasureAccess().getRule();
	}
	
	//BasicInformation returns BasicInformation:
	//    {BasicInformation}
	//    'BasicInformation'
	//    ;
	public BasicInformationElements getBasicInformationAccess() {
		return pBasicInformation;
	}
	
	public ParserRule getBasicInformationRule() {
		return getBasicInformationAccess().getRule();
	}
	
	//Title returns Title:
	//    {Title}
	//    'Title'
	//    ;
	public TitleElements getTitleAccess() {
		return pTitle;
	}
	
	public ParserRule getTitleRule() {
		return getTitleAccess().getRule();
	}
	
	//Image returns Image:
	//    {Image}
	//    'Image'
	//    ;
	public ImageElements getImageAccess() {
		return pImage;
	}
	
	public ParserRule getImageRule() {
		return getImageAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
