/*
 * generated by Xtext 2.36.0
 */
package no.ntnu.tdt4250.recipe.dsl.ui.tests;

import com.google.inject.Injector;
import no.ntnu.tdt4250.recipe.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RecipeDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("no.ntnu.tdt4250.recipe.dsl.RecipeDSL");
	}

}
