/*
 * generated by Xtext 2.36.0
 */
package no.ntnu.tdt4250.recipe.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import no.ntnu.tdt4250.recipe.dsl.RecipeDSLRuntimeModule;
import no.ntnu.tdt4250.recipe.dsl.RecipeDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RecipeDSLIdeSetup extends RecipeDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RecipeDSLRuntimeModule(), new RecipeDSLIdeModule()));
	}
	
}
