/*
 * generated by Xtext 2.36.0
 */
package no.ntnu.tdt4250.recipe.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class RecipeDSLIdeModule extends AbstractRecipeDSLIdeModule {
}
